name: Deploy
env:
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Set up Terraform
        working-directory: src
        run: terraform init
      - name: Apply Terraform changes
        working-directory: src
        run: terraform apply -auto-approve
